name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERNAME }}
        password: ${{ secrets.DOCKERTOKEN }}

    - name: Build and Push Docker Image
      working-directory: ./app  # Cambiar al directorio donde está tu código
      run: |
        docker build -t as-laboratorio-8-web .
        docker tag as-laboratorio-8-web:latest ${{ secrets.DOCKERNAME }}/as-laboratorio-8-web:latest
        docker push ${{ secrets.DOCKERNAME }}/as-laboratorio-8-web:latest  # Corregir la imagen para que coincida con el nombre utilizado en docker push

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.CLOUDJSON }}
        project_id: ${{ secrets.CLOUDNAME }}

    - name: Authenticate to GKE
      uses: simenandre/setup-gke-gcloud-auth-plugin@v1

    - name: Configure kubectl
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: autopilot-cluster-1
        location: us-central1

    - name: Deploy to Kubernetes
      working-directory: ./k8s  # Cambiar al directorio donde están tus archivos Kubernetes
      run: |
        kubectl apply -f bbdd-deployment.yaml
        kubectl apply -f service-bd.yaml
        kubectl apply -f front-web-deployment.yaml
        kubectl apply -f loadBalancer.yaml
        kubectl rollout restart deployment db-deployment
        kubectl rollout restart deployment front-web-deployment
